### PR TITLE
Optimize SC translation suggestions

### PR DESCRIPTION
**Pull request by DreamGallery**
suggestions comment start with ////.
There is no direct modification. 
Whether to adopt it depends on @Dreamink0.

### CODE REVIEW

**Comment by Dreaminko** [comment]
收到，正在修改。
第70行开始的期中考试1、2并非追加练习，而大概是未实装的Master模式中两段期中考试，
163、164行的理由同上。

试镜译为考试主要是由于国内大部分玩家的习惯。

**Comment by Dreaminko** [comment]
第115行参阅支援卡原文，实际效果为增加P点数数量，故不作修改
image

**Comment by Dreaminko** [comment]
其余修改已采纳，感谢您的贡献！

**Comment by DreamGallery** [comment]
> 第70行开始的期中考试1、2并非追加练习，而大概是未实装的Master模式中两段期中考试。

原来还有个master阶段，那可能是吧，不过的确也没看到期中期末追加练习的文本在哪

**Comment by vertesan** [comment]
Hi @DreamGallery, thanks for contributing to hatsuboshi-library. 

Looks like you were discussing something with @Dreamink0 and have already come to a conclusion which is reflected in #10.
Since there is no actual modification in this PR I'm going to close it if you have nothing more to discuss.

**Pull request closed without merging**
